name: toolchain
on:
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  toolchain:
    name: Toolchain
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Hisilicon [HI3516CV100]
          - {"platform": "hi3516cv100"}
          
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build toolchain
        run: |
          CONFIG=$(find br-ext-chip-* -name ${{matrix.platform}}_lite_defconfig)
          GCC=$(make BOARD=${CONFIG} toolname).tgz
          URL=https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG_NAME}/${GCC}
          echo ${URL}
          if ! wget -q --spider ${URL}; then
            sed -i "/BR2_TOOLCHAIN_EXTERNAL.*/d" ${CONFIG}
            echo BR2_PACKAGE_HOST_GDB=y >> ${CONFIG}
            echo BR2_PACKAGE_AWS_WEBRTC=y >> ${CONFIG}
            make BOARD=${CONFIG} br-source
            make BOARD=${CONFIG} br-sdk
            SDK=$(find output/images -name *_sdk-buildroot.tar.gz)
            mv ${SDK} ${GCC}
            echo GCC=${GCC} >> ${GITHUB_ENV}
          fi

      - name: Upload toolchain
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          files: ${{env.GCC}}
